---
title: "課堂練習"
date: "9/12/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(reticulate) #
use_python("D:\\ANCODA1\\envs\\myEnvironment2\\python.exe",
           required = T)
use_condaenv("myEnvironment2", required = T)
```

```{python}
a=5
type(a) # check class type
  ```
```

# conda安裝方式
conda_install("myEnvironment2", # 沙盒環境名稱
              c("numpy","pandas")) # 要安裝的modules

```{python}
string = 'very good'
string2 = 'I am very good' 
type(string)
numInteger = 3
type(numInteger)
#len(numInteger)
numFloat = 3.
type(numFloat)
#len(numFloat)
```


```{python}
logiT=True
type(logiT)
logiF=False
type(logiF)
```

```{python}
logiT+logiT+logiF
```

```{python}
list1 = [1,True,'apple',[1,2,3],(1,True),'bird','cat',['a','b','c']]
len(list)
```
```{python}
listA=[1,2,True]
listA
type(listA)
listB=[1,["a","b"],True] # nested list
listB
type(listB)
```
```{python}
var1, var2 ,var3 = listA
```

```{python}
var1
var2
var3
```

```{python}
a,*b = listA
a; type(a)
b; type(b)
```
```{python}
gradeTuple=('aden',80,79,80,10,10,20,30,40,'boy','girl')
name , *grade , gender1, gender2

print('----------------------')
name
print('--------------')
grade
print('------------------')
gender1
print('------------------')
gender2
print('------------------')
```


```{python}
listY = [1,1,3,2,1,0,2]
set(listY)
list(set(listY))
```
del list


```{python}
setY = set(listY)
setY

listY2 = list (setY)
listY2
```


```{python}
listY=[1,1,3,0,1,0,2]
list(set(listY))
```

```{python}
listA
```

```{python, eval=F}
for i in listA:
  i
```


```{python}
listc = [1,2,[2,2,2]]
for i in listc[2]:
  i
```

```{python}
tupleC=(1,["a","b"],True)
type(tupleC)
print(tupleC)
```




```{python}
listA = [('Mary','John'),('A2838','C8898'),(89,73)]
```

```{python}
len(listA) 
listA[0] 
listA[0][1] 

type(listA[0])
type(listA[0][1])
```

```{python}
studentID2="4107732882"
type(studentID2)
studentID2[3]
```
```{python}
studentId=4107732882
studentId3=str(studentId)
studentId3[3]
type(studentId)
```

#selet number
```{python student number example}
listA=['A','B','C','D','E','F','G','H','I','J']
listA
len(listA)
listA[0:5:1]
listA[0:5]
listA[0:5:2]
listA[:4] 
```


```{python}
listA
'--------------'
listA[-2:5:-1]
'--------------'
listA[-2:-6:-1]
'--------------'
listA[-5:-1:1]
'--------------'
listA[-5:] 
```

```{python}
listA
listA[1:]
listA[:-2]
listA[:-1]
```


#not irregular to choice the number
```{python}
[listA[0],listA[2],listA[7]]
```
```{python}
[listA[index] for index in [1,8,3,4]]
```

```{python}
listB=[2,5,-1,31,-22,3,17,25]

[listB[index] for index in [0,6,7]]
```

```{python}
listB=[2,5,-1,31,-22,3,17,25]
listB[0]
```


















