---
title: "課堂練習"
date: "9/12/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(reticulate)
use_python("D:\\ANCODA1\\envs\\myEnvironment2\\python.exe",
           required = T)
use_condaenv("myEnvironment2", required = T)
```



```{python}
def myfun(x,y):
  return x+y
```

```{python}
dict_myfuns={
    'fun1':myfun,
    'fun2':myfun2
}
```


```{python}
dict_myfuns['fun1](1,3)
```




```{python}
(lambda x, y: x + y)(2, 3)
```


```{python}
fun=lambda x,y:x+y

fun(2,3)
```

```{python}
import requests
response=requests.get("https://cloud.culture.tw/frontsite/trans/SearchShowAction.do?method=doFindTypeJ&category=3")
danceInfo=response.json()
```


```{python}
lenList = list([])

for i in range(len(danceInfo)):
     lenList.append(len(danceInfo[i]["showInfo"]))
```

```{python}
listA = []
for i in range(len(danceInfo)):
    listA.append(len(danceInfo[i]['showInfo']))

```
```{python}
total = 0
for i in range(listA):
  total += i
  
print(suma)
```


```{r}
View(py$danceInfo)
```


```{python}
sum(lenList)
```





```{python}
dict_example = {
    'list': [1, 3, -7, 4, 9, -5, 4],
    'dict': {
        "日期": [2001,2002,2003],
        "金額": [21000,33000,45880]
        },
    'matrix': [
        [2,5,4],
        [2,-1,3]]
}


print("list")
x=dict_example["list"]
x
[i for i in x]
[i for i in range(len(x))]
[i for i in enumerate(x)] # 產生tuple iterates
```

```{python}
M=dict_example['matrix']
M
```






